ChuyenDeASPNET/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChuyenDeASPNET.Context;
using ChuyenDeASPNET.Models;

namespace ChuyenDeASPNET.Controllers
{
    public class ProfileController : Controller
    {
        ASPNETEntities objASPNETEntities = new ASPNETEntities();
        // GET: Profile
        public ActionResult ProfileMain()
        {
            HomeModel objHomeModel = new HomeModel();
            // Lấy danh sách sản phẩm và danh mục từ cơ sở dữ liệu
            objHomeModel.ListProduct = objASPNETEntities.Products.ToList();
            objHomeModel.ListCategory = objASPNETEntities.Categories.ToList();
            return View(objHomeModel);
        }
        public ActionResult Order()
        {
            return View();
        }
        public ActionResult Seller()
        {
            return View();
        }
        public ActionResult Setting()
        {
            return View();
        }
        public ActionResult Wishlist()
        {
            return View();
        }
        public ActionResult Address()
        {
            return View();
        }
    }
}

ChuyenDeASPNET/Controllers/ShoppingController.cs
using ChuyenDeASPNET.Context;
using ChuyenDeASPNET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Controllers
{
    public class ShoppingController : Controller
    {
        // GET: Shopping
        ASPNETEntities objASPNETEntities = new ASPNETEntities();
        public ActionResult Cart()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddtoCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.ProductID.Equals(id))
                    return i;
            return -1;  
        }

        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.ProductID == Id);
            Session["cart"] = li;
            
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
            
        }

    }
}

ChuyenDeASPNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Alistyle</title>
    <link href="~/Content/images/ico.png" rel="shortcut icon" type="image/x-icon">


    <!-- jQuery -->
    <script src="~/Scripts/js/jquery-2.0.0.min.js"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js"></script>


    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />

    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" rel="stylesheet" />

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" />

    <link href="~/Content/css/responsive.css" rel="stylesheet" />

    <!-- custom javascript -->
    <script src="~/Scripts/js/script.js"></script>
</head>
<body>

    <!-- ========================= Header  ========================= -->
    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="@Url.Action("Index", "Home")" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">Tất cả</option>
                                    <option value="codex">Đặc biệt</option>
                                    <option value="comments">Tốt nhất</option>
                                    <option value="content">Mới nhất</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Nhập tên sản phẩm">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Tìm kiếm
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                @if (Session["idUser"] != null)
                                {
                                    <!-- Hiển thị các liên kết cho người dùng đã đăng nhập -->
                                    <ul style="list-style-type: none; padding-left: 0;">
                                        <li>
                                            <a href="~/Home/Logout" class="btn btn-warning">
                                                <i class="fa fa-sign-out"></i> Đăng xuất
                                            </a>
                                        </li>
                                    </ul>
                                }
                                else
                                {
                                    <!-- Hiển thị biểu tượng tài khoản cho người dùng chưa đăng nhập -->
                                    <div>
                                        <a href="~/Home/Register" class="btn btn-outline-primary">
                                            <i class="fa fa-user-plus"></i> Đăng ký
                                        </a>
                                        <a href="~/Home/Login" class="btn btn-outline-success">
                                            <i class="fa fa-sign-in"></i> Đăng nhập
                                        </a>
                                    </div>
                                }
                            </div>




                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                        @*<span class="notify">1</span>*@
                                    </div>
                                    <small class="text">Tin nhắn</small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="@Url.Action("Order", "Profile")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store"></i>
                                    </div>
                                    <small class="text">Shop</small>
                                </a>
                            </div>
                            <div class="widget-header">
                                <a href="@Url.Action("Cart", "Shopping")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                        @*<span class="notify" id="CartCount">
                                            @(Session["count"] != null ? Session["count"] : "0")
                                        </span>*@
                                    </div>
                                    <small class="text">Giỏ hàng</small>
                                </a>
                            </div>


                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Danh mục </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">iPhone</a>
                                <a class="dropdown-item" href="#">Laptop</a>
                                <a class="dropdown-item" href="#">Phụ kiện</a>
                                
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Vận chuyển</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="#">Dịch vụ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Người bán</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav ml-md-auto">
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">Tiếng Việt</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Tiếng Anh</a>
                                <a class="dropdown-item" href="#">Tiếng Pháp</a>
                                <a class="dropdown-item" href="#">Tiếng Trung</a>
                                
                            </div>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->
    <!-- ========================= Header End ========================= -->
    <div class="container body-content">
        @RenderBody()
    </div>

    <!-- ========================= Footer  ========================= -->
    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Thương hiệu</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Apple</a></li>
                            <li> <a href="#">Samsung</a></li>
                            <li> <a href="#">Xiaomi</a></li>
                            <li> <a href="#">Huawei</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Chung</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Về chúng tôi</a></li>
                            <li> <a href="#">Đối tác</a></li>
                            <li> <a href="#">Tìm cửa hàng</a></li>
                            <li> <a href="#">Điều khoản</a></li>
                            <li> <a href="#">Sitemap</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Trợ giúp</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Liên hệ</a></li>
                            <li> <a href="#">Hoàn tiền</a></li>
                            <li> <a href="#">Trạng thái</a></li>
                            <li> <a href="#">Thông tin</a></li>
                            <li> <a href="#">Thời gian làm việc</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Tài khoản</h6>
                        <ul class="list-unstyled">
                            <li> <a href="@Url.Action("Login", "Home")"> Đăng nhập </a></li>
                            <li> <a href="@Url.Action("Register", "Home")"> Đăng ký </a></li>
                            <li> <a href="@Url.Action("Order", "Profile")"> Hồ sơ </a></li>
                            <li> <a href="@Url.Action("Cart", "Shopping")"> Giỏ hàng </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Kênh</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Chính sách bảo mật | Điều khoản sử dụng | Thông tin người dùng | Hướng dẫn yêu cầu pháp lý</p>
                <p class="text-muted"> &copy 2019 Alistyle, Mọi quyền được bảo lưu </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= Footer End ========================= -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>