ChuyenDeASPNET/Controllers/PaymentController.cs
using ChuyenDeASPNET.Context;
using ChuyenDeASPNET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        ASPNETEntities objASPNETEntities = new ASPNETEntities();
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                // lấy thông tin từ giỏ hàng trong session
                var istCart = (List<CartModel>)Session["cart"];

                // tạo dữ liệu cho Order
                Order objOrder = new Order();
                objOrder.Name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objOrder.UserId = int.Parse(Session["idUser"].ToString());
                objOrder.CreatedOnUtc = DateTime.Now;
                objOrder.Status = 17;

                objASPNETEntities.Orders.Add(objOrder);

                // lưu thông tin vào bảng Order
                objASPNETEntities.SaveChanges();

                // Lấy OrderId vừa tạo để lưu vào bảng OrderDetail
                int orderId = objOrder.Id;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();

                foreach (var item in istCart)
                {
                    OrderDetail obj = new OrderDetail();
                    obj.Quantity = item.Quantity;
                    obj.OrderId = orderId;
                    obj.ProductId = item.Product.ProductID;
                    lstOrderDetail.Add(obj);
                }

                objASPNETEntities.OrderDetails.AddRange(lstOrderDetail);
                objASPNETEntities.SaveChanges();
                Session["cart"] = null; // Thêm dòng này để xóa giỏ hàng
            }

            return View();
        }
    }
}

ChuyenDeASPNET/Controllers/ShoppingController.cs
using ChuyenDeASPNET.Context;
using ChuyenDeASPNET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuyenDeASPNET.Controllers
{
    public class ShoppingController : Controller
    {
        // GET: Shopping
        ASPNETEntities objASPNETEntities = new ASPNETEntities();
        public ActionResult Cart()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddtoCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = objASPNETEntities.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.ProductID.Equals(id))
                    return i;
            return -1;  
        }

        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.ProductID == Id);
            Session["cart"] = li;
            
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
            
        }

    }
}

ChuyenDeASPNET/Views/Shopping/AddtoCart.cshtml
@model IEnumerable<ChuyenDeASPNET.Models.CartModel>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Shopping")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi khi xóa trong giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr id="product-@item.Product.ProductID">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.ProductImage" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.ProductImage</a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <input type="text" value="@item.Quantity" />
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@item.Product.Price</var>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.ProductID" id="productid" />
                                            <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>

                                            <a href="" class="btn btn-light" id="removecart"> Remove</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <p>Không có sản phẩm trong giỏ hàng</p>
                            }


                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <a href="#" class="btn btn-primary float-md-right"> Make Purchase <i class="fa fa-chevron-right"></i> </a>
                        <a href="#" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Coupon code">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Apply</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">USD 568</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Discount:</dt>
                            <dd class="text-right">USD 658</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right  h5"><strong>$1,650</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="images/misc/payments.png" height="26">
                        </p>

                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>

ChuyenDeASPNET/Views/Shopping/Cart.cshtml
    @model IEnumerable<ChuyenDeASPNET.Models.CartModel>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <script type="text/javascript">
        $(function () {
            $("#removecart").click(function () {
                var model = {};
                //lấy id sản phẩm
                model.Id = $("#productid").val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Remove", "Shopping")',
                    data:  JSON.stringify(model) ,
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function () {
                        $('#CartCount').text(@Session["count"] - 1);
                        $("#product-" + model.Id).remove();
                    },
                    error: function () {
                        alert("Lỗi trong khi thêm vào giỏ hàng!");
                    }
                });
                return false;
            });
        });
    </script>

    <section class="section-content padding-y">
        <div class="container">
            <div class="row">
                <main class="col-md-9">
                    <div class="card">

                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                    <th scope="col" class="text-right" width="200"> </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr id="product-@item.Product.ProductID">
                                            <td>
                                                <figure class="itemside">
                                                    <div class="aside"><img src="~/Content/images/items/@item.Product.ProductImage" class="img-sm"></div>
                                                    <figcaption class="info">
                                                        <a href="#" class="title text-dark">@item.Product.ProductName</a>
                                                    </figcaption>
                                                </figure>
                                            </td>
                                            <td>
                                                <input type="text" size="2" value="@item.Quantity" />
                                            </td>
                                            <td>
                                                <div class="price-wrap">
                                                    <var class="price">@String.Format("{0:N0}", item.Product.Price)</var>

                                                </div> <!-- price-wrap .// -->
                                            </td>
                                            <td class="text-right">
                                                <input type="hidden" value="@item.Product.ProductID" id="productid" />
                                                <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>

                                                <a href="" class="btn btn-light" id="removecart"> Xóa</a>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <div style="text-align: center; width: 100%; margin: 20px 0;">
                                        <p style="font-size: 16px; font-weight: bold;">Không có sản phẩm trong giỏ hàng<br />Hãy tiếp tục mua sắm!</p>
                                    </div>
                                }



                            </tbody>
                        </table>

                        <div class="card-body border-top">
                            <a href="@Url.Action("Index", "Payment")" class="btn btn-primary float-md-right"> Thanh toán <i class="fa fa-chevron-right"></i> </a>
                            <a href="@Url.Action("Index", "Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Trang chủ</a>
                        </div>
                    </div> <!-- card.// -->

                    <div class="alert alert-success mt-3">
                        <p class="icontext"><i class="icon text-success fa fa-truck"></i> Đảm bảo nhận hàng 1-2 tuần</p>
                    </div>

                </main> <!-- col.// -->
                <aside class="col-md-3">
                    <div class="card mb-3">
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <label>Có mã giảm giá?</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="" placeholder="Nhập mã giảm giá">
                                        <span class="input-group-append">
                                            <button class="btn btn-primary">Áp dụng</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div> <!-- card-body.// -->
                    </div>  <!-- card .// -->
                    <div class="card">
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <div class="card-body">

                                    <dl class="dlist-align">
                                        <dt>Giá bán:</dt>
                                        <dd class="text-right">@String.Format("{0:N0}", item.Product.Price) đ</dd>

                                    </dl>
                                    <dl class="dlist-align">
                                        <dt>Giảm giá:</dt>
                                        <dd class="text-right">0đ</dd>
                                    </dl>
                                    <dl class="dlist-align">
                                        <dt>Tổng:</dt>
                                        <dd class="text-right"><strong>@String.Format("{0:N0}", item.Product.Price) đ</strong></dd>

                                    </dl>
                                    

                                </div> <!-- card-body.// -->
                            }
                        }
                        else
                        {
                            <div class="card-body">

                                <dl class="dlist-align">
                                    <dt>Giá bán:</dt>
                                    <dd class="text-right">0đ</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Giảm giá:</dt>
                                    <dd class="text-right">0đ</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Tổng:</dt>
                                    <dd class="text-right  h5"><strong>0đ</strong></dd>
                                </dl>
                                

                            </div> <!-- card-body.// -->
                        }
                        
                    </div>  <!-- card .// -->
                </aside> <!-- col.// -->
            </div>

        </div> <!-- container .//  -->
    </section>